---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.8.3
    app.quarkus.io/commit-id: 0d0742498947170a7fdf6ea1ab407dd7efdc0178
    app.quarkus.io/vcs-uri: https://github.com/jeremyrdavis/devnexus2024-msa-openai.git
    app.quarkus.io/build-timestamp: 2024-04-05 - 10:48:17 +0000
  labels:
    app.kubernetes.io/name: devnexus2024-msa-openai
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: devnexus2024-msa-openai
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8082
  selector:
    app.kubernetes.io/name: devnexus2024-msa-openai
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.8.3
    app.quarkus.io/commit-id: 0d0742498947170a7fdf6ea1ab407dd7efdc0178
    app.quarkus.io/vcs-uri: https://github.com/jeremyrdavis/devnexus2024-msa-openai.git
    app.quarkus.io/build-timestamp: 2024-04-05 - 10:48:17 +0000
  labels:
    app.kubernetes.io/name: devnexus2024-msa-openai
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: devnexus2024-msa-openai
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: devnexus2024-msa-openai
      app.kubernetes.io/version: 0.0.1-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.8.3
        app.quarkus.io/commit-id: 0d0742498947170a7fdf6ea1ab407dd7efdc0178
        app.quarkus.io/vcs-uri: https://github.com/jeremyrdavis/devnexus2024-msa-openai.git
        app.quarkus.io/build-timestamp: 2024-04-05 - 10:48:17 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: devnexus2024-msa-openai
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/jeremydavis/devnexus2024-msa-openai:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: devnexus2024-msa-openai
          ports:
            - containerPort: 8082
              name: http
              protocol: TCP
