---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.8.3
    app.quarkus.io/vcs-uri: https://github.com/jeremyrdavis/devnexus2024-msa-openai.git
  labels:
    app.kubernetes.io/name: devnexus2024-msa-openai
    app.kubernetes.io/managed-by: quarkus
  name: devnexus2024-msa-openai
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8082
  selector:
    app.kubernetes.io/name: devnexus2024-msa-openai
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.8.3
    app.quarkus.io/vcs-uri: https://github.com/jeremyrdavis/devnexus2024-msa-openai.git
  labels:
    app.kubernetes.io/name: devnexus2024-msa-openai
    app.kubernetes.io/managed-by: quarkus
  name: devnexus2024-msa-openai
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: devnexus2024-msa-openai
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.8.3
        app.quarkus.io/vcs-uri: https://github.com/jeremyrdavis/devnexus2024-msa-openai.git
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: devnexus2024-msa-openai
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPENAI_KEY
              valueFrom:
                secretKeyRef:
                  key: OPENAI_KEY
                  name: devnexus2024-msa-secrets
          image: docker.io/jeremydavis/devnexus2024-msa-openai
          imagePullPolicy: Always
          name: devnexus2024-msa-openai
          ports:
            - containerPort: 8082
              name: http
              protocol: TCP
